### ISSUE TITLE
Error when loading model: ValueError: Model type mistral3 not supported.

### ISSUE THREAD

**Issue by MStraeten** [lmstudio-ai/mlx-engine#129]
lmstudio 0.3.13 Build2 with LM Studio mlx v0.10.0
mistral-small-3.1-24b-instruct-2503
https://huggingface.co/mlx-community/Mistral-Small-3.1-24B-Instruct-2503-6bit

**Comment by ArjunDivecha** [comment]
I have the same issue, with all versions

**Comment by matthieuHenocque** [comment]
I have the same issue.

**Comment by danieldomicianocosta** [comment]
Same issue here

**Comment by keel** [comment]
Same issue, wait for the update

**Comment by neilmehta24** [comment]
Getting #130 merged is a pre-requisite. cc @Blaizzy

**Comment by Blaizzy** [comment]
How can I help?

**Comment by neilmehta24** [comment]
I am seeing that the following four models are not passing unit tests:
```
Florence 2
Paligemma 2
Llama vision
Gemma 3
```

For example:
`python3.11 -m mlx_vlm.generate --prompt "what is your name" --model ~/.cache/lm-studio/models/mlx-community/paligemma2-3b-pt-896-4bit --image http://images.cocodataset.org/val2017/000000039769.jpg`
returns
`[broadcast_shapes] Shapes (1,256,1152) and (1,4096,1152) cannot be broadcast.`

**Comment by Blaizzy** [comment]
Hey Neil

I just tested paligemma2-3b-896-4bit with mlx-vlm 0.1.21 and transformers (4.50.0 + v4.51.0.dev0)

And it couldn't replicate the issue.

![Image](https://github.com/user-attachments/assets/194b0071-3f5f-4434-a466-96074157ef8f)

![Image](https://github.com/user-attachments/assets/41f08dca-a502-4973-b7b6-67cff17c9c4a)

**Comment by neilmehta24** [comment]
This feature should be good to go extremely soon, I have all test cases passing on my end

@Blaizzy thanks for checking, turns out I borked my some of my cached models while developing this PR ([Fix qwen2_vl patching](https://github.com/lmstudio-ai/mlx-engine/pull/130/commits/1a7450f204e9b790009aaa55136080b16c61c344))

**Comment by Blaizzy** [comment]
My pleasure!❤️

**Comment by neilmehta24** [comment]
This is fixed with MLX runtime version `0.11.1`, which is out now

**Comment by MStraeten** [comment]
thanks for the fix

**Comment by easychen** [comment]
```
Failed to load model

Error when loading model: ValueError: Model type mistral3 not supported.
```

I still get an error message. I'm using mlx-community/Mistral-Small-3.1-24B-Instruct-2503-4bit    

<img width="487" alt="Image" src="https://github.com/user-attachments/assets/a10145db-eb4a-4d09-a9e2-705bb7def49f" />

**Comment by easychen** [comment]
> > ```
> > Failed to load model
> > 
> > Error when loading model: ValueError: Model type mistral3 not supported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I still get an error message. I'm using mlx-community/Mistral-Small-3.1-24B-Instruct-2503-4bit
> > <img alt="Image" width="487" src="https://private-user-images.githubusercontent.com/1294760/426809166-a10145db-eb4a-4d09-a9e2-705bb7def49f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5ODI3OTksIm5iZiI6MTc0Mjk4MjQ5OSwicGF0aCI6Ii8xMjk0NzYwLzQyNjgwOTE2Ni1hMTAxNDVkYi1lYjRhLTRkMDktYTllMi03MDViYjdkZWY0OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjZUMDk0ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVkNzQ4NjE5ODI1ZGJhOWFiZWE3NThkOTQ1YzY5N2EyMGU5Y2YzZjY2NDAxYjRiNjZhNzVjYjEyMGVmODdiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z9csZjJEtpU36d3MbNMRniiQnuu9ba0g_IKeJWKRZvA">
> 
> After installing v0.11.1, I had to manually change MLX version in the Default Selection from v0.10 to v0.11.1.



> > ```
> > Failed to load model
> > 
> > Error when loading model: ValueError: Model type mistral3 not supported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I still get an error message. I'm using mlx-community/Mistral-Small-3.1-24B-Instruct-2503-4bit
> > <img alt="Image" width="487" src="https://private-user-images.githubusercontent.com/1294760/426809166-a10145db-eb4a-4d09-a9e2-705bb7def49f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5ODI3OTksIm5iZiI6MTc0Mjk4MjQ5OSwicGF0aCI6Ii8xMjk0NzYwLzQyNjgwOTE2Ni1hMTAxNDVkYi1lYjRhLTRkMDktYTllMi03MDViYjdkZWY0OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjZUMDk0ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVkNzQ4NjE5ODI1ZGJhOWFiZWE3NThkOTQ1YzY5N2EyMGU5Y2YzZjY2NDAxYjRiNjZhNzVjYjEyMGVmODdiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z9csZjJEtpU36d3MbNMRniiQnuu9ba0g_IKeJWKRZvA">
> 
> After installing v0.11.1, I had to manually change MLX version in the Default Selection from v0.10 to v0.11.1.

Thank you for the reminder, this is indeed the issue

<img width="888" alt="Image" src="https://github.com/user-attachments/assets/de0447fb-912e-431a-bcfa-3ae348a5b2fb" />
