### ISSUE TITLE
Support for Llama 4

### ISSUE THREAD

**Issue by rkyymmt** [lmstudio-ai/mlx-engine#132]
```
Error when loading model: ValueError: Model type llama4 not supported.
```

**Comment by neilmehta24** [comment]
Done w/ release 0.12.1

**Comment by gsgxnet** [comment]
With the mlx-community 6bit model <https://huggingface.co/mlx-community/Llama-4-Scout-17B-16E-Instruct-6bit>  I still see the same error.  Must I use the lmstudio-community version announced?
